version: "2"

services:
  asknow:
    #build: ./docker/
    image: index.docker.io/smartdataanalytics/asknow-site:latest
    container_name: asknow
    environment:
      - REPO=https://github.com/AskNowQA/AskNow-Website
      - BRANCH=master
    ports:
      - 8080:80
    volumes:
      - /var/www/asknow.sda.tech/:/data/jekyll/

  watchtower:
    image: v2tec/watchtower
    restart: unless-stopped
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: asknow --interval 30